version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"      
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/app/mongodb-models

volumes:
  mongo-data:
